"""Added username

Revision ID: 5252f9a2b582
Revises: 44689628b2f1
Create Date: 2022-06-20 21:52:06.609627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5252f9a2b582'
down_revision = '44689628b2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
