"""Added password field

Revision ID: 666597a2c0c2
Revises: 19bd89a9749d
Create Date: 2022-06-20 16:57:34.358157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666597a2c0c2'
down_revision = '19bd89a9749d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
